registryItems:
  applications:
  - {pulsar-scenario: nq 0}
  instances:
  - {pulsar-scenario: nq 0}
  operationNames:
  - pulsar-scenario: [Pulsar/test/Producer, /case/pulsar-case, Pulsar/test/Consumer/test]
segmentItems:
- applicationCode: pulsar-scenario
  segmentSize: ge 3
  segments:
  - segmentId: not null
    spans:
    - operationName: Pulsar/test/Producer
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: MQ
      startTime: nq 0
      endTime: nq 0
      componentId: 73
      componentName: ''
      isError: false
      spanType: Exit
      peer: not null
      peerId: 0
      tags:
      - {key: mq.broker, value: not null}
      - {key: mq.topic, value: 'test'}
    - operationName: /case/pulsar-case
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 14
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/pulsar-scenario/case/pulsar-case'}
      - {key: http.method, value: GET}
  - segmentId: not null
    spans:
    - operationName: Pulsar/Producer/Callback
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: MQ
      startTime: nq 0
      endTime: nq 0
      componentId: 73
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      tags:
      - {key: mq.topic, value: 'test'}
      refs:
      - {parentEndpointId: 0, parentEndpoint: /case/pulsar-case, networkAddressId: 0, entryEndpointId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${pulsar-scenario[0]}', parentServiceInstanceId: nq 0, networkAddress: '', entryEndpoint: /case/pulsar-case, entryServiceInstanceId: nq 0 }
  - segmentId: not null
    spans:
    - operationName: Pulsar/test/Consumer/test
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: MQ
      startTime: nq 0
      endTime: nq 0
      componentId: 74
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: mq.broker, value: not null}
      - {key: mq.topic, value: 'test'}
      refs:
      - {parentEndpointId: 0, parentEndpoint: /case/pulsar-case, networkAddressId: 0, entryEndpointId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${pulsar-scenario[0]}', parentServiceInstanceId: nq 0, networkAddress: not null, entryEndpoint: /case/pulsar-case, entryServiceInstanceId: nq 0}
